name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions: 
  contents: write
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: free disk space
        run: |
         sudo swapoff -a
         sudo rm -f /swapfile
         sudo apt clean
         docker rmi $(docker image ls -aq)
         df -h
      #- name: Free disk space
      #  run: |
      #   sudo apt-get autoremove -y >/dev/null 2>&1
      #   sudo apt-get autoclean -y >/dev/null 2>&1
      #   sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
      #   docker rmi $(docker image ls -aq) >/dev/null 2>&1
      - uses: actions/checkout@v3
            
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: .
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: Deploy
      #  uses: JamesIves/github-pages-deploy-action@v4
      #  with:
      #       branch: main
      #       folder: . 
      #- name: Build the site in the jekyll/builder container
      #  run: |
      #   docker run \
      #   -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
      #   jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
